os:
- osx
language:
- javascript
env:
  global:
  - NODE_VERSION=6
  - secure: ZzfzZGUliJ0ronvHdWl87WZOrFK9MJQPMT1opzKYlEfrRyoxqzxRM0tdj4MIxXV95c8jN8iOq0sLVWkRcE/thlMRIN49ox9Dcgyg06JZaBXH7fii3AFedxEUOkPTe03GFrJLPZSKT6iGJBroKRb0fB0DqMhfNJzPdaOXYieAVpBTFMSHr6xrENftUoScE2gSBJIJr3FdwpewuJ3XCnoQGPV7TyxKfQg2g2OFG7+Y6/+TQjSYnNqgUwC2YfG5ZxQ5hEGKBWXTgKa/IiqqXRjBBE7790N8v//8W0A98/73QLiPgsKWPKHwKW6mcj8ovwHFGU1cbX/F6t2nwIRv6Yz3/9P1cp/b/O6hGZitFs7YcFOZJaeGscYIg8/4pQxJniN7ErE/o12is2w9P8VxTp045sSaJAfSRxBFtdYcMwwLNf1gyEm4tB0QDcAgOqVoEaUCwsEmgsIAh6SxLgEwynm5vAeuqblhMoPgYViYGrmBBmkTBRj/FANGZW2ZwVxUVqQ8UTYeAZzkWjjNL2B02aF2ZW6WPXlwFQ8s68nev/U11ndfK6uCSuW8Ibnq7Me9NbZaqvrxViK4nIo5kcQ89G61oICbtntnlYl0brBAh1XIjMIln7yyj0nt25sb3Gp0D7XNkTa7IG7jvBgbXMI9/Ye3Aro+Bb+1MQcM4NaJ3MwdZao=
  - secure: X6KaTTToe11LbPnKxcqJA6/3jBkdd16DeI1Id9yQ4WLJyCPvVLEyW+gJdVB/6RfxMDly9sTSREnTv1VEJY5/V9xLlRfuQV39P+wtL4iQlSjNYoUrryCyU6LeprAf1712ERna3fAVEMoy5nHeer7BjdM5B5XTQTnCDAYTq0bXvO9UraQH7As10xlnGrW0rCBXN/BcPjcqUuRn26Gd7bDlsjl6/22Wx4cjzPWLsBd+QAR1PUazX7lv2UT6T3i4xibfBMyi+7uCM9gHG8jNNZ8slc/+4IxY/1wHfa2aTs/XrFkmvzygwPnz2Y88MW/U6G2WgX0Cd631OX18WMAl0yC0sHfIzJPQZPHEWPC2QilRNHySpgE/6u5xTcf9/drGWc4LdULxARHuzt3gLWJWZU/ZY7ELJ8ZSDQ5aru1jtY+uVlSFtONjsiCUA5h3Uy++i0N2xXDi0Q7XaxnAiLfaiV+003RH/L4WjnRPqImLyd7o8c7cqEwZio92PW+Hic4xvrlIgJmYNf2uL1anfqmxv4eLqlfULLsAqFFcuhye6XwoEWMM7w5YTX9M/s8VjqK61am1P0RS1/C8roFxrcjir6rmkJc2QRVLMlJWVQVV/kxQWzQi6b+AofdemXxEuspQMWkw6+2hi+qAojW3ltUNVvADQhLf/xaN0NOK6OmTtz7ZzxA=
  - secure: p1cCe6Jzc55Pl7O/bJvCdLBR/wMZsRqt4rTDm9WRxtdvhWoEaDUMK23l8msOzpaFXV9hd1Sb+W+AXwpiddgvVEdVXqTKJkS0hlVZjblvhxGFS4ATQkx3ZVgKeMBiLT6dP4DzwOcZOBvheFvLsbppAbKPfD0dIXxnYwdZEJbe5o78Ve/usS6Od23vC3iCzCeF3SRBY5uFtsARMAyk6URT80qiXZwNMtmNUOPtUTQD5Vlr+6yUCM6wO8c/Hpu7rDfZ1fVPYuYXFwvGWwd5v72jciDjvNFlMTrvV49TGpNFyfmBBaHfc0nuVrt6tbEdYEsYN1KNjk64+lTRU2LXXY5jEJGmlEbJ32n4sOxXSyhAnb0STWZS05M/N5Tcq4tvlm03ix4kmw5cJiMmt9a6HWu3SLwVuer6vhAkFYbvwCA5BDiHC8HgyVzRjTA299kdKKZIqlyjp5zvvlxWI73jihWs7oQfv7iMVUSrIqnXBdvATfDZdaxNoFGkM6aVHCIFdLyE/OBeum+z36eZCi6aJQi21qZUbMUtA8V43AWCnLfLi2LeF/wHVmlIru3OnTJ/vUIgE1SM9OHDE1HlxzDs0GtTqIhoyRN5LdNnyZZeNiUmm+QWRginld4j5hXeHkNConYO5ilvP628fFWHHmKYovmf3Hr9VfTGk3EG0pV7srw5cJY=
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - $HOME/.npm
install:
- npm prune
- npm install
script:
- ./node_modules/grunt-cli/bin/grunt build
deploy:
  provider: releases
  api_key:
    secure: EeL6Oq+4RjTwS+6tn6IS6lozpmDTUC5q0QE9teikwjwR3KM+B9f13sUs9VFQPs7OznXtPPs+hHXS0f4Cg4Qo70AMiMPnC7BFQtrnNGzM4Ri+z1XXISuvNpyLcMCcCUTv6ucdN8fygi/WL+TvLdAAjdKNAoliyUBhlX0oAaLFAp3G+Obk8aluF+KO2jmXdoPymEKVOdlo2CK3UHiayesrCd6bTyq7B8FABRfwhxeiiGFR+ZtV2fXrXaS3180TBe/akjl5mt6Mgzlo1TDBKabn1ruo4pkyqD0hzqOxitCmvegZYuY6v2BqdxYUuNb88lxqp6CxEXx5hd8SI+lalOwYzfKtDmT8dD+6dYciAkxt7b3L6C35idSxtA7r7+JLobXotrTQQF6K/bJJYhNd/j+zF4Trn8NycBrzCfgwiwtQja7ZDN6eUcOwv4I1WjGnPyAbmhXvZQvsVOs3iBdU7lJNYINhwpCWKwYH1ibR8qqjJESIiLVfbrObgzmeErnvNcalM4Z9rqrPd8bSgnStToKwhpAT9cPNERG/njxQfa9Km44+6q/W2h5Hzj6q4uVVXvtRt5uFkV5nBD2YGoDeCN0IotFmyB1yzkfNCPiRqZC9YruooyoAnM/O1Nv5oChsqR2gq+0kI3Y98nCsDODO29hCYrl47gp1HG3DM71AWdThf/Q=
  file: dist/*
  on:
    tags: true
