language:
- node_js
node_js:
- '6'
env:
  global:
  - GH_REF: github.com/entrylabs/entryjs.git
  - GH_REPO: https://github.com/entrylabs/entryjs.git
cache:
  directories:
  - node_modules
  - $HOME/.npm
branches:
  only:
  - master
before_script:
- chmod +x ./scripts/build.sh
- chmod +x ./scripts/deploy.sh
install:
- npm prune
- npm install
script:
- ./scripts/build.sh
# - ./scripts/deploy.sh
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
      branch: master
