language:
- node_js
node_js:
  - "6"
env:
  global:
    - GH_REF: github.com/kimorkim/entryjs.git
    - GH_REPO: 'https://github.com/kimorkim/entryjs.git'
    - secure: >-
        nA4wNQyLGVCImbv9L6++RaLdkNwcltdpKkpSPukuFnBcy3g4r9aF2iKxKgLYZG5OGLwMq9kyfInGwR27q3BRETsC8dDbZA4UCYlm/KKyT3rZ5o0by6zTPdLHgRLDYpaju9WpODx1sTBPS1nVcxCwcIWhB0xZS/zotFldQrtgmfzYC0yp1P5biaHV1vU7j67MwJ5AXMsYxkeqo5clsUzeL4VvZM0yRQteirI9RsqBr5b+zx2wz1HXjrom++W63/wbVheMadYahIQeKwzJ9v3i1I8wVEAYmY/vF13HBfEgCCRJ6Ja0Xa4EqrUWHogFwJAkishIdk0l7VfLIa0xf2KktjRKDqAqsfdEWP+M1dVknClcDGUNL2prv/1tovGRA7rKEDLOP3B1PRRvQPfJBTzf8wEJ5+VMjLXVOMKF29sdHpaU/elk/UGFereQwUKtkfaeDmoi3mhPCtz0/RlGl3MGopH8mfN3x7JxryDLEYSYiaVirHL1zRiF1U5HvKPM4u38pDUbuZ7BMhTJBWqY3QjvhNK4w0Uof2q2/ujoRW1d1xb8e+8ft9QE/rF4ZeUyyKE2fdS3AQdc6NQ/78cQf3Hyamy9U/0OGKmxKLEHm9nrT1PQEwnurSj9rhLzsZ47AAi1qvSkKj1di4nBAAFryRyJHBEZUHQGBgdekMW6uqCfGtQ=
cache:
  directories:
  - node_modules
  - $HOME/.npm
branches:
  only:
    - master
before_script:
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
install:
- npm prune
- npm install
script:
- ./scripts/build.sh
- ./scripts/deploy.sh
# deploy:
#   provider: releases
#   api_key:
#     secure: EeL6Oq+4RjTwS+6tn6IS6lozpmDTUC5q0QE9teikwjwR3KM+B9f13sUs9VFQPs7OznXtPPs+hHXS0f4Cg4Qo70AMiMPnC7BFQtrnNGzM4Ri+z1XXISuvNpyLcMCcCUTv6ucdN8fygi/WL+TvLdAAjdKNAoliyUBhlX0oAaLFAp3G+Obk8aluF+KO2jmXdoPymEKVOdlo2CK3UHiayesrCd6bTyq7B8FABRfwhxeiiGFR+ZtV2fXrXaS3180TBe/akjl5mt6Mgzlo1TDBKabn1ruo4pkyqD0hzqOxitCmvegZYuY6v2BqdxYUuNb88lxqp6CxEXx5hd8SI+lalOwYzfKtDmT8dD+6dYciAkxt7b3L6C35idSxtA7r7+JLobXotrTQQF6K/bJJYhNd/j+zF4Trn8NycBrzCfgwiwtQja7ZDN6eUcOwv4I1WjGnPyAbmhXvZQvsVOs3iBdU7lJNYINhwpCWKwYH1ibR8qqjJESIiLVfbrObgzmeErnvNcalM4Z9rqrPd8bSgnStToKwhpAT9cPNERG/njxQfa9Km44+6q/W2h5Hzj6q4uVVXvtRt5uFkV5nBD2YGoDeCN0IotFmyB1yzkfNCPiRqZC9YruooyoAnM/O1Nv5oChsqR2gq+0kI3Y98nCsDODO29hCYrl47gp1HG3DM71AWdThf/Q=
#   file_glob: true
#   file: dist/*
#   skip_cleanup: true
#   on:
#     tags: true
#     all_branches: true
