language:
- node_js
node_js:
- '6'
env:
  global:
  - GH_REF: github.com/entrylabs/entryjs.git
  - GH_REPO: https://github.com/entrylabs/entryjs.git
  - secure: PvKc75o3MUeUPXijkMS4Y/lMgCS2xjADKFDuiO2cqJgcroXgiEAMCftPjwD5og7lLy76Xvr1v0nT82y3ZOOcd5QBU5GRrPmNW5S06UZLP5vGiW0APFE1myrWVfotdiBNyW/8SeAmTdos/wxyzN6vweiEe7sxALSaB427rGRcR2BA5gEQTJ2+v8CTZm2OuhLX9FBTmcjqPI4s9d+UdLNUHkn/pJ6uDn0oqAZFRjhvDUhWE5Me912TVyE34sZDyH0HEK3g1MX7VRWm+JRAItxJ6z/t2VUrumTz3uNkV4u9PjHCOnhyIbfM3avRXypyZ/FL0iAu4ycjwprjkSV/K3Aet/kuUs+Hh0+nDleQzBkDHILJoj0LNGKgwOvSOmc60WEGfOc1jQUbO1rkUxYdlc/bBV5tIK69W5745cOynL7e77UZLCrvzz0af4ajKjk9PqfNkw75IBb70efkW3f0aVfJT3Q21ScjfOYUlqBGp5qlG8xkeFMktZxIq9rSMdxNdRSrng2nJgTopuY4wvzIfGgI5GvH73cRddfRvLJgJEvG8dEzLM7uEBs/UiTUHyrw6ZVM8DBk2RCZGXBewpcd0s1JPL5Fx54wpxIDaolXQzenkTjMktHjSZXzC04Zc6mgBlROJR8AKeAZgu/R1yKRgLtCQFW2HP051RV06MlLt6Pyg2Y=
cache:
  directories:
  - node_modules
  - $HOME/.npm
branches:
  only:
  - travis/test
  # - master
before_script:
- chmod +x ./scripts/build.sh
- chmod +x ./scripts/deploy.sh
install:
- npm prune
- npm install
script:
- ./scripts/build.sh
deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
      branch: travis/test
      # branch: master
