name: Entry Build and Deploy

on:
  push:
    branches:
      - 'deploy2/**'
      - deploy2/build_with_actions

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: bahmutov/npm-install@v1
      - name: entry build
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
          TOOL_NODE_FLAGS: '--max-old-space-size=4096'
        run: |
          npm run prod
  execute-script:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Execute build.sh
        run: |
          sh ./scripts/build.sh
      - name: Execute deploy.sh
        run: |
          sh ./scripts/deploy.sh
