name: Entry Build and Deploy

on:
  push:
    branches:
      - 'deploy2/**'

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 10.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - name: entry build
        run: |
          npm run prod
  execute-script:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Execute build.sh
        run: |
          sh ./scripts/build.sh
      - name: Execute deploy.sh
        run: |
          sh ./scripts/deploy.sh
